import { fetchRoute } from "./vars";

export const petitions = {
  register: fetchRoute + "/users",
  login: fetchRoute + "/users/login",
  getTemplate: fetchRoute + "/template",
  addTemplate: fetchRoute + "/template",
  getListPatient: fetchRoute + "/attended/today",
  updateAttended: fetchRoute + "/attended/update/",
  getMedications: fetchRoute + "/medications",
  getIndications: fetchRoute + "/indications",
  postPatient: fetchRoute + "/patients",
  getPatients: fetchRoute + "/patients",
  getHistory: fetchRoute + "/historys/",
  addProxCita: fetchRoute + "/quotes/",
  updateHistory: fetchRoute + "/historys/",
  getEnterprise: fetchRoute + "/enterprise",
  postEnterprise: fetchRoute + "/enterprise",
  getParametros: fetchRoute + "/parameters",
  deleteParametros: fetchRoute + "/parameters/",
  addListAttended: fetchRoute + "/attended/",
  addConsulta: fetchRoute + "/consulta/",
  getReporte: fetchRoute + "/consulta",
  citasMes: fetchRoute + "/quotes/mes/all",
  updateAttended: fetchRoute + "/attended/update/",
  consultasHoy: fetchRoute + "/consulta/procesados/today",
  consultasDia: fetchRoute + "/consulta/procesados/dia/",
  consultasMes: fetchRoute + "/consulta/procesados/mes/",
  consultasPersonalizada: fetchRoute + "/consulta/procesados/personalizado/",
  guardadosRecipe: fetchRoute + "/guardados/recipe/",
  guardadosInforme: fetchRoute + "/guardados/informe/",
  guardadosReferencia: fetchRoute + "/guardados/referencia/",
  guardadosResumen: fetchRoute + "/guardados/resumen/",
  guardadosCita: fetchRoute + "/guardados/cita/",
  guardadosReposo: fetchRoute + "/guardados/reposo/",
  updatePatient: fetchRoute + "/patients/"
};